### PR TITLE
Filter expressions for DataFrames

### PR DESCRIPTION
**Pull request by dlorson**
Adds a "smart text field" to PanelTables using the "Table" data provider (i.e. having DataFrames as the underlying data source).

## UI

A single search field in the navigation bar of each DataFrame table.

Screen Shot 2019-05-10 at 17 02 45

## Expression parsing

Uses nearley.js (MIT https://github.com/kach/nearley/blob/master/LICENSE.txt) and a small custom grammar to parse expressions of the form:

### Single queries 

When a single term without whitespace is entered, all rows are retained in which one or more of the properties matches the term.

Examples:
```
BRCA        # doesn't matter if 'BRCA' is contained in the sample_name or gene property
BRCA1
8277_
```

### Property conditions

One or more conditions can be entered, separated by `and` (or `AND`).
Each condition tests a single property (and a property can be tested by multiple conditions).  Only rows matching *all* conditions will be retained.

Conditions can test numeric properties:
```
amplicon_order is 1
amplicon_order = 1
amplicon_order >= 1
amplicon_order between 1 and 10
```
Or string properties:
```
sample_name = 'S1'       # exact match
sample_name like 'S1_'     # contains
```

So a more specific query could be:
```
sample_name like 'S1' and amplicon_order < 10 and final_dq between 0.7 and 1.3
```

### Invalid expression

When the expression fails to parse, the filter field will reflect this:

Screen Shot 2019-05-10 at 17 16 46

## Performance

Filtering has some latency for global expressions O(nRow x nCol) so it's debounced.
Filtering operations are run on the column-major DF structure to avoid creating row-based copies.

## New DataFrames

Since the filtering is performed at the data provider level (Table.js), the underlying DataFrame is unchanged (e.g. filters will not apply when creating a new view from this DF).
Of course this could be adjusted to what would work best.

### CODE REVIEW

**Comment by dlorson** [comment]
An initial attempt, feel free to leave feedback!

**Comment by dlorson** [comment]
Indeed, there should be no concern for arbitrary code execution as only a small set of expressions (str/numeric comparisons returning a boolean value) are allowed, parsed, and then evaluated.

There is still a bug with the interaction between filtering and sorting as you mention.  On it!

**Comment by dlorson** [comment]
I changed the way the sort and filter indexes are constructed:
* filtering is applied first
* sorting sorts the filtered indices according to their respective values in the dataframe
* sorting changed to lodash implementation (stable, and follows the underlying DF order in case of ties).

Tested filtering/sorting combinations in different orders; did not observe any unexpected interactions/behavior.

**Comment by bramslabbinck** [comment]
This looks really GREAT and will improve dataframe handling A LOT!  I have only tested it on the amplicon statistics dataframe

two issues I noticed:
- the like statement does not seem to work? Eg. chrom like 'chr1_'
- searching and filtering is done based on the column keys and not the displayed names. We don't know all these keys by heart and there can be a lot of columns. The fastest solution would be to change the popup when you hover over a column name to display the dataframe column key instead of the dataframe column name? A long road is possibly a column selector where you can add a column to the search bar through a button/field/selector. @MichaelVyverman what is your opinion on this?

**Comment by MichaelVyverman** [comment]
I agree that it is difficult in the beginning to find the column keys. For now, you can click the open button for a row and you will see all of the column keys in the popup that appears. 
- A tooltip seems like an option. 
- Using a column selector, I am for the idea of typing a selector character, such as "#" and that will show a list of possible column keys like in an autocomplete edit box. The current situation is fine for me though.

**Comment by dlorson** [comment]
Great you like it!
Agree that column identifier hinting would be very useful as a future addition, an inline autocomplete + `#` sounds like the fastest option for the user.

@bramslabbinck the example for the "like" statement was slightly misleading, the `_` is not a placeholder character, it just finds instances of the query string within the property.  So `chrom like 'chr1'` should match chr1, chr11, grchr37_chr11, ...  There's no option to evaluate regexes yet.

**Pull request merged**
